In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

file_path = 'Iris.csv'
data = pd.read_csv(file_path)

#class for logistic regression
class Logistic_Regression:
  def __init__(self):
    self.theta=0

  def hypothsis(self , X):
    #Stack feature space with 1
    x_dot = np.hstack((X,np.ones((X.shape[0],1))))
    h = np.dot(x_dot , self.theta.reshape(-1,1))
    return 1/(1+np.exp(-h))

  def loss(self , X , Y):
    h = self.hypothsis(X)
    loss = -np.mean((Y*np.log(h) + (1-Y)*np.log(1-h)))
    return loss

  def der_loss(self , X , Y):
    h = self.hypothsis(X)
    x_dot = np.hstack((X , np.ones((X.shape[0],1))))
    return np.mean((h-Y)*x_dot , axis=0).reshape(-1,1)

  def gradient(self , der , alpha):
    return self.theta - alpha*der

  def Train(self,X,Y,alpha=0.01,max_iteration = 100,loss_iteration=20):
    self.theta = np.random.rand(X.shape[1]+1,1)
    print(f"X.shape = {X.shape}\nY.shape = {Y.shape}\ntheta.shape = {self.theta.shape}")
    for i in range(max_iteration):

      d = self.der_loss(X,Y)
      if i%loss_iteration==0:
        print(f"Loss after {i} iteration = {self.loss(X,Y)}")

      self.theta = self.gradient(d,alpha)

    print(f"Gradient = {d}")
    print(f"Loss after {max_iteration} = {self.loss(X,Y)}")
    print(f"Hypothesis Shape = {self.hypothsis(X).shape}")



  def Predict_Class(self, X):
    prediction = self.hypothsis(X)
    prediction[prediction>0.5] = 1
    prediction[prediction<=0.5] = 0
    return prediction


  def Predict_Confidence(self , X):
    return self.hypothsis(X)

  def Get_weights(self):
    return self.theta

#Extract the Labels and Features from the dataframe

X = data.drop('Id', axis=1).drop('Species',axis=1).values
Y1 = data.iloc[:,data.shape[1]-1].values.reshape(-1,1)
Y2 = data.iloc[:,data.shape[1]-1].values.reshape(-1,1)
Y3 = data.iloc[:,data.shape[1]-1].values.reshape(-1,1)

#convert catgorical data  to numerical
# Setosa vs (Virginica and Versicolor)
Y1[Y1=='Iris-setosa'] = 1
Y1[Y1=='Iris-virginica'] = 0
Y1[Y1=='Iris-versicolor'] =0
Y1 = Y1.astype(int)# Convert the object datatype to int
# Virginica vs (Setosa and Versicolor)
Y2[Y2=='Iris-setosa'] = 0
Y2[Y2=='Iris-virginica'] = 1
Y2[Y2=='Iris-versicolor'] = 0
Y2 = Y2.astype(int)# Convert the object datatype to int
# Versicolor vs (Setosa and Versicolor)
Y3[Y3=='Iris-setosa'] = 0
Y3[Y3=='Iris-virginica'] = 0
Y3[Y3=='Iris-versicolor'] =1
Y3 = Y3.astype(int)# Convert the object datatype to int


#Splitting the dataset in train and test
X1_train , X1_test , Y1_train , Y1_test = train_test_split(X,Y1,test_size=0.3,random_state=42)
X2_train , X2_test , Y2_train , Y2_test = train_test_split(X,Y2,test_size=0.3,random_state=42)
X3_train , X3_test , Y3_train , Y3_test = train_test_split(X,Y3,test_size=0.3,random_state=42)

#Initializing the instances

set1 = Logistic_Regression()
set2 = Logistic_Regression()
set3 = Logistic_Regression()
#Training
print("Training")
print("Set1\n")
set1.Train(X1_train,Y1_train,0.001,5000,1000)
print("Set2\n")
set2.Train(X2_train,Y2_train,0.001,5000,1000)
print("Set3\n")
set3.Train(X3_train,Y3_train,0.001,5000,1000)

Training
Set1

X.shape = (105, 4)
Y.shape = (105, 1)
theta.shape = (5, 1)
Loss after 0 iteration = 8.181231191281501
Loss after 1000 iteration = 0.3914802341327033
Loss after 2000 iteration = 0.25504268968150484
Loss after 3000 iteration = 0.18526996004858204
Loss after 4000 iteration = 0.1447440173375715
Gradient = [[-0.02747044]
 [-0.07343721]
 [ 0.11148217]
 [ 0.05075693]
 [-0.01426239]]
Loss after 5000 = 0.11868013667192627
Hypothesis Shape = (105, 1)
Set2

X.shape = (105, 4)
Y.shape = (105, 1)
theta.shape = (5, 1)
Loss after 0 iteration = 4.139738657975107
Loss after 1000 iteration = 0.5122478049699035
Loss after 2000 iteration = 0.31137197985320264
Loss after 3000 iteration = 0.21464001907547892
Loss after 4000 iteration = 0.1620484173928724
Gradient = [[-0.03161114]
 [-0.08008313]
 [ 0.1222265 ]
 [ 0.05658729]
 [-0.01615441]]
Loss after 5000 = 0.12987036345991143
Hypothesis Shape = (105, 1)
Set3

X.shape = (105, 4)
Y.shape = (105, 1)
theta.shape = (5, 1)
Loss after 0 iteration = 2.5411627045879484
Loss after 1000 iteration = 0.2694281481947278
Loss after 2000 iteration = 0.1928964017689504
Loss after 3000 iteration = 0.1492859747398283
Loss after 4000 iteration = 0.12163125140072312
Gradient = [[-0.02353784]
 [-0.06312002]
 [ 0.09659798]
 [ 0.04408819]
 [-0.01235505]]
Loss after 5000 = 0.10266734817178495
Hypothesis Shape = (105, 1)

In [4]:
#Testing/Predicting Confidence
print(f"------------------------Testing-----------------------------")

print(f"--------------------Set1----------------------\n")
pc1 = set1.Predict_Confidence(X1_test)
print(f"Result {np.array_equal(pc1,Y1_test)}")
print(f"--------------------Set2----------------------\n")
pc2 = set2.Predict_Confidence(X2_test)
print(f"Result {np.array_equal(pc2,Y2_test)}")
print(f"--------------------Set3----------------------\n")
pc3 = set3.Predict_Confidence(X3_test)
print(f"Result {np.array_equal(pc2,Y2_test)}")
i=1
pc1[i] , pc1[i] , pc2[i] , Y1_test[i] , Y2_test[i] , Y3_test[i]

------------------------Testing-----------------------------
--------------------Set1----------------------

Result False
--------------------Set2----------------------

Result False
--------------------Set3----------------------

Result False

(array([0.83463837]),
 array([0.83463837]),
 array([0.79959294]),
 array([1]),
 array([1]),
 array([1]))

In [ ]:
#Testing/Predicting Class
print(f"------------------------Testing-----------------------------")

print(f"--------------------Set1----------------------\n")
c1 = set1.Predict_Class(X1_test)
print(f"Result {np.array_equal(c1,Y1_test)}")
print(f"--------------------Set2----------------------\n")
c2 = set2.Predict_Class(X2_test)
print(f"Result {np.array_equal(c2,Y2_test)}")
print(f"--------------------Set3----------------------\n")
c3 = set3.Predict_Class(X3_test)
print(f"Result {np.array_equal(c2,Y2_test)}")

(array([[-0.14594036],
        [ 1.12574622],
        [-1.31236756],
        [ 0.29039196],
        [ 0.43316974]]),
 array([[-0.26548696],
        [ 1.03333515],
        [-0.79718481],
        [-0.52956001],
        [ 0.52929662]]),
 array([[-0.29161583],
        [ 1.03355503],
        [-1.07738263],
        [ 0.21008352],
        [ 0.86204374]]))

In [ ]:
X1_test , Y1_test, X2_test, Y2_test

np.array_equal(Y1, Y2)

True

In [5]:
np.where(Y1==1) , np.where(Y2==1) , np.where(Y3==1)

((array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        dtype=int64),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0], dtype=int64)),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        dtype=int64),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0], dtype=int64)),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
         34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        dtype=int64),
  array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0], dtype=int64)))

In [6]:
k = data.iloc[:,5].values

In [8]:
data

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0      1            5.1           3.5            1.4           0.2       1
1      2            4.9           3.0            1.4           0.2       1
2      3            4.7           3.2            1.3           0.2       1
3      4            4.6           3.1            1.5           0.2       1
4      5            5.0           3.6            1.4           0.2       1
..   ...            ...           ...            ...           ...     ...
145  146            6.7           3.0            5.2           2.3       0
146  147            6.3           2.5            5.0           1.9       0
147  148            6.5           3.0            5.2           2.0       0
148  149            6.2           3.4            5.4           2.3       0
149  150            5.9           3.0            5.1           1.8       0

[150 rows x 6 columns]

In [9]:
data = pd.read_csv(file_path)

In [10]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
Y1 , Y2

(array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]),
 array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]]))

In [12]:
data = pd.read_csv(file_path)

In [94]:
data

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0      1            5.1           3.5            1.4           0.2       0
1      2            4.9           3.0            1.4           0.2       0
2      3            4.7           3.2            1.3           0.2       0
3      4            4.6           3.1            1.5           0.2       0
4      5            5.0           3.6            1.4           0.2       0
..   ...            ...           ...            ...           ...     ...
145  146            6.7           3.0            5.2           2.3       0
146  147            6.3           2.5            5.0           1.9       0
147  148            6.5           3.0            5.2           2.0       0
148  149            6.2           3.4            5.4           2.3       0
149  150            5.9           3.0            5.1           1.8       0

[150 rows x 6 columns]

In [13]:
y = data.iloc[:,data.shape[1]-1]
y1 = y.values

In [14]:
y1

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype=object)

In [15]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
y = y.astype(int)
np.where(y==1)

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       dtype=int64),)

In [19]:
data

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0      1            5.1           3.5            1.4           0.2       0
1      2            4.9           3.0            1.4           0.2       0
2      3            4.7           3.2            1.3           0.2       0
3      4            4.6           3.1            1.5           0.2       0
4      5            5.0           3.6            1.4           0.2       0
..   ...            ...           ...            ...           ...     ...
145  146            6.7           3.0            5.2           2.3       0
146  147            6.3           2.5            5.0           1.9       0
147  148            6.5           3.0            5.2           2.0       0
148  149            6.2           3.4            5.4           2.3       0
149  150            5.9           3.0            5.1           1.8       0

[150 rows x 6 columns]